server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    # Remove trailing slash
    rewrite ^/(.*)/$ /$1 permanent;

    root /app;
    index index.html;
    try_files $uri $uri/index.html =404;

    error_page 404 /404.html;
}
